FROM continuumio/miniconda3

WORKDIR /home/app

RUN apt-get update -y 
RUN apt-get install nano unzip
RUN apt install curl -y

RUN curl -fsSL https://get.deta.dev/cli.sh | sh
COPY requirements.txt /dependencies/requirements.txt
RUN pip install -r /dependencies/requirements.txt

COPY . /home/app

EXPOSE 8501

#CMD ["streamlit", "run", "--server.port=8501", "app.py"]

CMD ["sh", "-c", "streamlit run app.py --server.port=${PORT:-8501}"]"]
